from glob import glob
from typing import Any, Dict, List, Optional, Tuple
from pathlib import Path
from tempfile import NamedTemporaryFile
import click
import re

import toml
from git import Repo
from platform_cli.groups.release import find_packages
from platform_cli.groups.base import PlatformCliGroup
from platform_cli.helpers import echo

from python_on_whales import docker, Container


def _merge_dep(acc: Dict[str, str], name: str, version: Any, source: Path) -> None:
    """Merge a single dep into the accumulator. Conflicts emit a warning and keep the first-seen pin."""
    if not isinstance(version, str):
        echo(
            f"warning: {source}: '{name}' has non-string version spec "
            f"({type(version).__name__}); skipping. Tabular pins aren't supported by gen-pixi.",
            "yellow",
        )
        return
    if name in acc and acc[name] != version:
        echo(
            f"warning: '{name}' pinned to both '{acc[name]}' and '{version}'; "
            f"keeping '{acc[name]}' (later seen in {source})",
            "yellow",
        )
        return
    acc[name] = version


def _aggregate_package_deps(
    package_manifests: List[Path],
) -> Dict[str, str]:
    """Walk each package's pixi.toml and union host- + run-dependencies."""
    deps: Dict[str, str] = {}
    for manifest in package_manifests:
        data = toml.load(manifest)
        pkg = data.get("package", {})
        for table in ("host-dependencies", "run-dependencies"):
            for name, version in pkg.get(table, {}).items():
                _merge_dep(deps, name, version, manifest)
    return deps


def _render_workspace_manifest(workspace_name: str, deps: Dict[str, str]) -> str:
    """Render a deterministic workspace pixi.toml. Deps sorted alphabetically."""
    lines = [
        "# AUTO-GENERATED by `platform ws gen-pixi`.",
        "# Edits here will be lost the next time the command runs.",
        "# Source of truth for per-package deps is each packages/*/pixi.toml.",
        "",
        "[workspace]",
        f'name = "{workspace_name}"',
        "channels = [",
        '  "http://localhost:8000",',
        '  "https://prefix.dev/robostack-kilted",',
        '  "https://prefix.dev/conda-forge",',
        "]",
        'platforms = ["linux-64"]',
        "",
        "[dependencies]",
    ]
    for name in sorted(deps):
        lines.append(f'{name} = "{deps[name]}"')
    lines.append("")
    return "\n".join(lines)


def _ensure_gitignore_entry(repo_root: Path, pattern: str) -> bool:
    """Append `pattern` to .gitignore if not already present. Returns True if the file was changed."""
    gitignore = repo_root / ".gitignore"
    existing = gitignore.read_text() if gitignore.exists() else ""
    if any(line.strip() == pattern for line in existing.splitlines()):
        return False
    if existing and not existing.endswith("\n"):
        existing += "\n"
    gitignore.write_text(existing + pattern + "\n")
    return True


def _is_single_package_repo(root_manifest: Path) -> bool:
    """A repo is single-package if its root pixi.toml declares a [package] block."""
    if not root_manifest.exists():
        return False
    return "package" in toml.load(root_manifest)


BASE_IMAGE = "ghcr.io/greenroom-robotics/ros_builder:iron-latest"


def get_auth_file() -> Dict[str, str]:
    entries = (Path().home() / ".gr" / "auth").read_text().strip().split("\n")
    matches = [re.match(r"export (?P<key>\w+)=(?P<value>.+)", e) for e in entries]
    return {m.group("key"): m.group("value") for m in matches if m}


def get_system_platform_path() -> Path:
    return Path.home() / "work/platform"


def ws_symlinks_to_platform_paths(
    workspace_path: Path, packages: Dict[Any, Any]
) -> Tuple[Dict[str, Path], Dict[str, Path]]:
    platform_paths = {}
    other_paths = {}
    for path in (workspace_path / "src").iterdir():
        if path.is_symlink():
            pkg_name = path.name
            pkg_path = path.resolve()
            if (
                pkg_path.parts[: len(get_system_platform_path().parts)]
                != get_system_platform_path().parts
            ):
                echo(f"Non platform based package: {pkg_path}", "yellow")
                other_paths[pkg_name] = pkg_path
            else:
                platform_paths[pkg_name] = pkg_path
    return platform_paths, other_paths


class Workspace(PlatformCliGroup):
    def create(self, cli: click.Group):
        @cli.group(help="CLI handlers associated with colcon workspaces")
        def ws():
            pass

        @ws.command(name="gen-pixi")
        @click.option(
            "--ros-distro",
            default="kilted",
            show_default=True,
            help="ROS distro for the dev shell's `ros-<distro>-desktop` meta-package.",
        )
        @click.option(
            "--check",
            is_flag=True,
            default=False,
            help="Print the rendered manifest to stdout instead of writing.",
        )
        def gen_pixi(ros_distro: str, check: bool):  # type: ignore
            """Generate a workspace pixi.toml from each packages/*/pixi.toml.

            Aggregates [package.host-dependencies] and [package.run-dependencies]
            from each sub-package, layers in dev tooling (colcon, rosdep,
            compilers, cmake, ninja, etc.), and writes the result to the repo
            root. The generated pixi.toml is added to .gitignore so it's never
            committed.

            For single-package repos (root pixi.toml has a [package] block),
            the root manifest is hand-maintained and this command is a no-op.
            """
            cwd = Path.cwd()
            root_manifest = cwd / "pixi.toml"

            if _is_single_package_repo(root_manifest):
                echo(
                    "Single-package repo detected (root pixi.toml has [package]). "
                    "The root manifest is hand-maintained; nothing to generate.",
                    "yellow",
                )
                return

            package_manifests = sorted(cwd.glob("packages/*/pixi.toml"))
            if not package_manifests:
                echo("No packages/*/pixi.toml found.", "red")
                raise click.Abort()

            deps = _aggregate_package_deps(package_manifests)

            # Always-on dev tooling. setdefault so an explicit pin in a
            # package's pixi.toml takes precedence over our defaults.
            for name, version in {
                f"ros-{ros_distro}-desktop": "*",
                "colcon-common-extensions": "*",
                "rosdep": "*",
                "compilers": "*",
                "cmake": "*",
                "ninja": "*",
                "make": "*",
                "pkg-config": "*",
            }.items():
                deps.setdefault(name, version)

            rendered = _render_workspace_manifest(cwd.name, deps)

            if check:
                click.echo(rendered)
                return

            root_manifest.write_text(rendered)
            echo(f"Wrote {root_manifest} ({len(deps)} deps)", "green")

            if _ensure_gitignore_entry(cwd, "/pixi.toml"):
                echo("Added '/pixi.toml' to .gitignore", "green")

        @ws.command(name="setup-proxy")
        @click.argument("container_name", type=str)
        def base_image():

            setup_proxy().callback()

        @ws.command(name="setup-proxy")
        @click.argument("container_name", type=str)
        def setup_proxy(container_name: str):  # type: ignore
            """Sets up the proxy for the workspace container"""

            if docker.container.exists(container_name):
                container = docker.container.inspect(container_name)
            else:
                echo(f"Container '{container_name}' not found", "red")
                return

            proxy_ip = "172.17.0.1"
            proxy_port = "3142"

            proxy_conf = f"""Acquire {{
    HTTP::proxy "http://{proxy_ip}:{proxy_port}";
    HTTPS::proxy "http://{proxy_ip}:{proxy_port}";
}}"""

            with NamedTemporaryFile() as f:
                f.write(proxy_conf.encode())
                f.flush()
                container.copy_to(f.name, "/etc/apt/apt.conf.d/01proxy")

        @ws.command(name="container")
        @click.option("--base-image", type=str, default=None, help="The base image to use")
        @click.option("--path", type=str, multiple=True, help="Paths to compile in the workspace")
        # @click.option("--debug-symbols", is_flag=True, show_default=True, default=False)
        # @click.option("--no-base", is_flag=True, default=False)
        # @click.argument("args", nargs=-1)
        def container(base_image: Optional[str], path: List[str]):  # type: ignore
            """Creates a container for the workspace"""

            base_image = base_image if base_image else BASE_IMAGE
            system_platform_path = get_system_platform_path()
            container_platform_path = Path("/platform")
            container_other_path = Path("/other_pkgs")
            container_home_path = Path("/home/ros")
            workspace_path = Path.cwd()
            container_name = f"platform_ws_{workspace_path.name}"

            packages = find_packages(workspace_path / "src")
            platform_paths, other_pkgs = ws_symlinks_to_platform_paths(workspace_path, packages)

            if docker.container.exists(container_name):
                container = docker.container.inspect(container_name)
                echo(f"Container '{container_name}' already exists - removing", "red")
                container.remove(force=True)

            echo(
                f"Creating container '{container_name}' for workspace {workspace_path}...", "green"
            )

            # workspace_volume = docker.volume.create(f"{container_name}_src", "local",
            #                                         options={
            #                                             "type": "overlay",
            #                                             "o": f"""lowerdir={workspace_path / "src"},upperdir={workspace_path / "workdir"},workdir={workspace_path / "tmp"}""",
            #                                             "device": "overlay"
            #                                         })

            other_volumes = [
                (p, container_other_path / pkg, "rw") for pkg, p in other_pkgs.items()
            ]

            container = docker.run(
                base_image,
                ["tail", "-f", "/dev/null"],
                name=container_name,
                envs=get_auth_file(),
                volumes=[
                    # (workspace_path / "src", "/home/ros/ws/src",  "ro"),
                    (system_platform_path, container_platform_path, "rw"),
                ]
                + other_volumes,
                workdir=container_home_path,
                detach=True,
                remove=False,
            )

            if not isinstance(container, Container):
                # Handle other possible return types
                raise TypeError("Expected a Container, but got a different type")

            echo(f"Container '{container_name}' created", "green")
            container.execute(
                ["mkdir", "-p", "ws/src"], tty=True
            )  # , "chown", "ros:ros", "/home/ros/ws"

            for p in platform_paths.values():
                p_rel = container_platform_path / p.relative_to(system_platform_path)
                container.execute(["ln", "-s", str(p_rel), "ws/src"], tty=True)

            for p in other_pkgs.values():
                p_rel = container_other_path / p.name
                container.execute(["ln", "-s", str(p_rel), "ws/src"], tty=True)

            container.execute(
                ["pip", "install", str(container_platform_path / "tools/platform_cli")], tty=True
            )
            container.execute(["platform", "pkg", "setup"], tty=True)
            # container.execute(["platform", "pkg", "refresh-deps"], tty=True)

            # how do we source the setup.bash files? needs to be ran as bash -l -c COMMAND
            # container.execute(["colcon", "build"], tty=True)

            # container.stop()

        @ws.command(name="symlink")
        @click.option("--package", type=str, multiple=True)
        def symlink(package: List[str]):  # type: ignore
            workspace_path = Path.cwd()
            platform_packages = find_packages(get_system_platform_path() / "packages")

            for p in package:
                if p not in platform_packages:
                    echo(f"Package '{p}' not found", "red")
                    return

                if (workspace_path / "src" / p).exists():
                    echo(f"Package '{p}' already exists in workspace", "yellow")
                    continue

                echo(f"Adding {p} to workspace as a symlink", "green")
                (workspace_path / "src" / p).symlink_to(platform_packages[p].package_path)

        @ws.command(name="versions")
        # @click.argument("package", type=str)
        def versions():  # type: ignore
            """Gets the versions of the packages in the workspace"""

            workspace_path = Path.cwd()
            packages = find_packages(workspace_path / "src")

            print(packages)
            for name, info in packages.items():
                if info.module_info is None:
                    continue

                repo = Repo(info.module_info.platform_module_path)
                for tag in repo.tags:
                    if tag.name.startswith(name):
                        print(tag)

        @ws.command(name="build-pkg")
        @click.option(
            "--package",
            type=str,
            help="Which package should we build.",
        )
        @click.option(
            "--version",
            type=str,
            help="The version number to assign to the deb",
            required=False,
            default="",
        )
        # add a flag to skip rosdep
        @click.option("--no-rosdep", type=bool, is_flag=True, default=False)
        def build_pkg(package: str, version: str, no_rosdep: bool):  # type: ignore
            """Builds a package in the workspace"""

            workspace_path = Path.cwd()
            container_ws = Path("/home/ros/ws")
            packages = find_packages(workspace_path / "src")
            container_name = f"platform_ws_{workspace_path.name}"
            container = docker.container.inspect(container_name)

            if package not in packages:
                echo(f"Package '{package}' not found", "red")
                return

            rel_path = packages[package].package_path.relative_to(workspace_path)

            container.execute(
                ["platform", "pkg", "clean"], tty=True, workdir=container_ws / rel_path
            )
            if not no_rosdep:
                container.execute(
                    ["platform", "pkg", "install-deps"], tty=True, workdir=container_ws / rel_path
                )
            container.execute(
                ["platform", "pkg", "build", "--version", version],
                tty=True,
                workdir=container_ws / rel_path,
            )
