name: Release

on:
  release:
    types:
      - created

jobs:
  pypi:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip
          pip3 install build
      - name: Build
        run: python3 -m build --sdist --wheel --outdir dist/
        shell: bash
      # - name: Upload
      #   uses: pypa/gh-action-pypi-publish@master
      #   with:
      #     repository_url: https://upload.pypi.org/legacy/
      #     password: ${{ secrets.PYPI_API_TOKEN }}
