name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  release:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - uses: pre-commit/action@v2.0.3

      - name: Install pyright
        run: pip install pyright

      - name: Install the cli
        run: pip install .

      - name: Test
        run: pyright

